### ISSUE TITLE
It seems to not has a trainning implementation in the repo?

### ISSUE THREAD

**Issue by PeiqinSun** [sniklaus/pytorch-liteflownet#12]
First, thanks to your pytorch implementation. But I couldn't find the training implementation of your repo.

**Comment by sniklaus** [comment]
Thank you for being interested in my reimplementation of LiteFlowNet! I am afraid that I do not provide training code, since I focused on replicating the official implementation only in terms of inference. I would be happy if someone forked this repository and adds this functionality though, it would definitely be useful!
