### ISSUE TITLE
Data augmentation using mean value

### ISSUE THREAD

**Issue by abrosua** [sniklaus/pytorch-liteflownet#22]
Hi, I have questions regarding the data augmentation that normalize the input tensor value using the mean RGB.

I notice that you put the [normalization](https://github.com/sniklaus/pytorch-liteflownet/blob/072061947c3fe1ba3996682a7b2ec6973c737e33/run.py#L303) (mean value subtraction) directly into the model class.

1. If we want to train the model, do we have to include this mean subtraction also? Or is it only for inference?

2. Suppose that I want to use your code to train a LiteFlowNet from scratch (with my own datasets*), does it means that I have to change the mean value according to my own datasets?

_*the mean value of my datasets are quite lower than the one that used in the original LiteFlowNet model (e.g., 0.171..)_

Thank you for your attention.
Regards

**Comment by sniklaus** [comment]
For a related discussion, please see: https://github.com/sniklaus/pytorch-liteflownet/issues/18

1. You can also decide not to do the normalization. If you decide to do the normalization, which is probably a good idea, then you need to make sure that the normalization during inference is the same as during training.
2. I would recommend you learn these values (PyTorch parameters), just like the original LiteFlowNet did. You could also pre-compute these values (average mean and maybe even the average standard deviation), which is how it is commonly done for image classification (and you already seem to have those values anyway).

You could also try to see what happens if you use the provided model but you update the normalization with the mean from your dataset. Maybe that yields better results for you.

**Comment by abrosua** [comment]
Thanks for the recommendations.

Suppose that I want to impose photometric augmentation (i.e., contrast, brightness, gaussian noise, etc) to the dataset for the training procedure. Should I perform the mean normalization before the photometric or after?

**Comment by sniklaus** [comment]
After. You can consider the normalization to be part of the network (your method) and the augmentation is just a way to broaden the statistics of the the dataset (input of your method).

**Comment by abrosua** [comment]
aaah I see, thanks again for your recommendations.
