### ISSUE TITLE
PyTorch 1.1.0

### ISSUE THREAD

**Issue by ncherel** [sniklaus/pytorch-liteflownet#30]
FYI the code is running fine using PyTorch 1.1.0.
Only change is to remove `align_corners=True` which is not defined for this version https://github.com/sniklaus/pytorch-liteflownet/blob/320a634ec4ffe15532e04dd50c07094719ec2a92/run.py#L55

This is the default behaviour prior to version 1.1.0 according to the [docs](https://pytorch.org/docs/stable/nn.functional.html#grid-sample)
> The default behavior up to version 1.2.0 was align_corners = True.

**Comment by sniklaus** [comment]
While maintaining this repository, I have made sure that it works with the newest PyTorch version. For example, I added the `align_corners` in eb1b09d9ba138a6d2f2f8348a9292603fbdfdeb0 since newer versions of PyTorch set it to `false` by default but the pre-trained model expects it to be set to `true` (it used to be `true` by default). In doing so, I have occasionally dropped support for older version such that it is easier for me to maintain.
