### ISSUE TITLE
Real-time inference?

### ISSUE THREAD

**Issue by FedericoVasile1** [sniklaus/pytorch-liteflownet#37]
Hi, I congrats for your work.
I would like to know whether at inference time is it possible to use this model as part of a framework that performs the online action detection task? (i.e. let's suppose I have an input stream video, is the model able to compute optical-flow features as the frames arrive, with real-time speed ?)

Thank you!

**Comment by sniklaus** [comment]
That depends on the resolution and frame-rate of the input video, as well as the GPU that you have. I would lean towards "no" regarding real-time inference though.

For more information on this topic, you might want to ask the authors of this paper in the official repository [1]. I am afraid that this repository is just a personal reimplementation and I am not affiliated with the paper otherwise.

[1] https://github.com/twhui/LiteFlowNet
